trigger:
  batch: true
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

schedules:
  - cron: '0 0 * * 0'
    displayName: Weekly build
    branches:
      include:
        - main
    always: true

resources:
  repositories:
    - repository: templates
      type: github
      name: osisoft/OSI-Samples
      endpoint: osisoft/OSI-Samples

variables:
  - template: '/miscellaneous/build_templates/variables.yml@templates'
  - name: CredFile
    value: test-config.js
  - name: CredFileLibrary
    value: product-readiness.piwebapi_jquery.js
  - name: analysisProject
    value: PIWebAPI_JQuery

jobs:
  - job: Tests
    pool:
      name: 00-OSIManaged-Test
      demands: COMPUTERNAME -equals $(buildAgent)
    steps:
      - template: '/miscellaneous/build_templates/config.yml@templates'
        parameters:
          fileOriginal: $(CredFile)
          fileLibrary: $(CredFileLibrary)

      - template: '/run-tests.yml'
        parameters:
          projectPath: $(Build.SourcesDirectory)/KarmaUnitTests/

      - template: '/miscellaneous/build_templates/analysis.yml@templates'
